global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'http://ec2-3-252-193-23.eu-west-1.compute.amazonaws.com:8080/'
          - 'http://ec2-3-252-193-23.eu-west-1.compute.amazonaws.com:80/'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
